# Sesi 4

In [2]:
import numpy as np

## Array

In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


## Creating Array

In [4]:
print(np.array.__doc__)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If obj

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
np.array(['test', 'string'])

array(['test', 'string'], dtype='<U6')

In [7]:
np.array([[1,2], [3,2], [4,5]])

array([[1, 2],
       [3, 2],
       [4, 5]])

In [8]:
np.array([[1,2,3], [5,3,2]], dtype=float)

array([[1., 2., 3.],
       [5., 3., 2.]])

In [9]:
print(np.zeros.__doc__)

zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
print(np.ones.__doc__)


    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        Array of ones with the given sha

In [13]:
dim = (3,3)
np.ones(dim)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
print(np.empty.__doc__)

empty(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, without initializing entries.

    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    --

In [15]:
np.empty(5)

array([6.95263850e-310, 1.20574765e-311, 1.20574765e-311, 1.20574765e-311,
       1.37932252e-312])

In [16]:
print(np.arange.__doc__)

arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections below for more information.

    Parameters
    ----------
    star

In [17]:
print(np.arange(4))
print(np.arange(1, 5, 2)) #(start, end, step)

[0 1 2 3]
[1 3]


In [18]:
np.arange(0, 5, .5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
np.array([1,2])
np.zeros(6)
np.zeros((4,5))
np.ones(5)
np.empty(5)
np.arange(3, 20, 4)

array([ 3,  7, 11, 15, 19])

## Add, Remove, Sort

In [20]:
# Append
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr = np.append(arr, [1,2])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [22]:
# Delete
arr = np.delete(arr, -1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [23]:
# Sort
arr2 = np.array([2,5,6,3,8,7,1])
arr2

array([2, 5, 6, 3, 8, 7, 1])

In [24]:
np.sort(arr2)

array([1, 2, 3, 5, 6, 7, 8])

## Shape & Size

In [25]:
arr = np.array([
    np.arange(3),
    np.arange(3,6),
    np.arange(6,9)
])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# ndim
arr.ndim

2

In [27]:
array_example = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        np.arange(9,13)
    ],
    [
        np.arange(13,17),
        np.arange(17,21),
        np.arange(21,25)
    ]
])
array_example

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [28]:
array_example.ndim

3

In [29]:
print(array_example)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [30]:
print(arr.size)
print(array_example.size)

9
24


In [31]:
print(arr.shape)
print(array_example.shape)

(3, 3)
(2, 3, 4)


In [32]:
arr_one = np.array([np.arange(1,6)])
arr_one

array([[1, 2, 3, 4, 5]])

In [33]:
print('Dimension :', arr_one.ndim)
print('Size :', arr_one.size)
print('Shape :', arr_one.shape)

Dimension : 2
Size : 5
Shape : (1, 5)


In [34]:
## Reshape
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [35]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [37]:
a.reshape(3,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [38]:
print(np.reshape.__doc__)



    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        changing fastest, and the last index changing slowest. Note that
        the 'C

## Convert 1D to 2D

In [39]:
a = np.arange(1,7)
a.shape

(6,)

In [40]:
a.reshape(1,6).shape

(1, 6)

In [41]:
a2 = a[np.newaxis]
print("Shape :", a2.shape)
print("Array :", a2)

Shape : (1, 6)
Array : [[1 2 3 4 5 6]]


In [42]:
row_vector = a[np.newaxis, :]
print("Shape :", row_vector.shape)
print("Array :", row_vector)

Shape : (1, 6)
Array : [[1 2 3 4 5 6]]


In [43]:
col_vector = a[:, np.newaxis]
print("Shape :", col_vector.shape)
print("Array :", col_vector)

Shape : (6, 1)
Array : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
print("Shape :", a.shape)
print("Array :", a)

Shape : (6,)
Array : [1 2 3 4 5 6]


In [45]:
b = np.expand_dims(a, axis=1)
print("Shape :", b.shape)
print("Array :", b)

Shape : (6, 1)
Array : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [46]:
c = np.expand_dims(a, axis=0)
print("Shape :", c.shape)
print("Array :", c)

Shape : (1, 6)
Array : [[1 2 3 4 5 6]]


## Indexing & Slicing

In [47]:
data = np.arange(1,6)
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3 4 5]
1
2
[1 2]
[2 3 4 5]
[4 5]


In [48]:
data = np.array([
    np.arange(1,5),
    np.arange(5,9),
    np.arange(9,13)
])
print("Shape :", data.shape)
print("Array : \n", data)

Shape : (3, 4)
Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
print(data[data>=5])

[ 5  6  7  8  9 10 11 12]


In [50]:
five_up = (data >= 5)

print(data[five_up])
print(data[data >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [51]:
divisible_by_2 = (data % 2 == 0)
print(data[divisible_by_2])

[ 2  4  6  8 10 12]


In [52]:
data_2 = data[(data > 2) & (data < 11)]
print(data_2)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [53]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr2 = arr[2:7]
arr2

array([3, 4, 5, 6, 7])

In [56]:
# Stack
a_1 = np.array([
    [1,1],
    [2,2]
])
a_2 = np.array([
    [3,3],
    [4,4]
])
np.vstack((a_1,a_2,a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2]])

In [57]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [58]:
# Split
arrSplit = np.array([
    np.arange(1, 13),
    np.arange(13, 25)
])
arrSplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
arrSplit.shape

(2, 12)

In [60]:
np.hsplit(arrSplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [61]:
np.vsplit(arrSplit, 2)[0]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

## Copy and View

In [62]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
a[0,0] = 10
a

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
b

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operation

In [68]:
a = np.array([1,2,3,4])
a.sum()

10

In [69]:
b = np.array([
    [1,1],
    [2,2]
])
b

array([[1, 1],
       [2, 2]])

In [70]:
b.sum(axis=0)

array([3, 3])

In [71]:
b.sum(axis=1)

array([2, 4])

In [72]:
b.sum()

6

In [73]:
import numpy as np

In [74]:
data = np.array([1,2])
data2 = np.array([3,4])
data2 ** data

array([ 3, 16])

In [75]:
ones = np.ones(2)
ones

array([1., 1.])

In [76]:
data + ones

array([2., 3.])

In [77]:
data*data

array([1, 4])

In [78]:
data/data

array([1., 1.])

## Broadcasting

In [79]:
data + 10

array([11, 12])

In [80]:
data * 10

array([10, 20])

In [81]:
array_example.max()

24

In [82]:
array_example.min()

1

In [83]:
array_example.sum()

300

In [84]:
array_example

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [85]:
A = np.array([[0.45, 0.17, 0.34, 0.55],
              [0.54, 0.051, 0.40, 0.556],
              [0.127, 0.824, 0.265, 0.569]])
A


array([[0.45 , 0.17 , 0.34 , 0.55 ],
       [0.54 , 0.051, 0.4  , 0.556],
       [0.127, 0.824, 0.265, 0.569]])

In [86]:
A.min(axis=1)

array([0.17 , 0.051, 0.127])

In [87]:
A.max(axis=0)

array([0.54 , 0.824, 0.4  , 0.569])

## Matrices

In [88]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [90]:
np.random.random((3,2))

array([[0.86439916, 0.25304396],
       [0.61743637, 0.64423718],
       [0.67755152, 0.31806058]])

In [91]:
data = np.array([[1,2], [3,4]])
data

array([[1, 2],
       [3, 4]])

In [92]:
one = np.ones((2,2))
one

array([[1., 1.],
       [1., 1.]])

In [93]:
print(data + one)

[[2. 3.]
 [4. 5.]]


In [94]:
one_row = np.ones((1,2))
one_row

array([[1., 1.]])

In [95]:
print(data + one_row)

[[2. 3.]
 [4. 5.]]


In [96]:
b = np.array([1,2])
print(data + b)

[[2 4]
 [4 6]]


In [97]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [98]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [99]:
np.dot(a_1, a_2).shape

(2, 2)

In [100]:
data = np.array([[1,2], [3,4], [5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [101]:
print(data[0])

[1 2]


In [102]:
print(data[0,1])

2


In [103]:
print(data[1:])

[[3 4]
 [5 6]]


In [104]:
print(data[:, 1])

[2 4 6]


## Matrix Agregation

In [105]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [106]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [107]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [108]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [109]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [110]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [113]:
ndarr = np.array([
    [
        [1,2],
        [3,4]
    ],[
        [5,6],
        [7,8]
    ]
])
ndarr.shape

(2, 2, 2)

In [114]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [115]:
print(np.random.random((4,3,2)))

[[[0.70188753 0.29739273]
  [0.77789471 0.7788221 ]
  [0.37374941 0.18217947]]

 [[0.7594552  0.13284219]
  [0.79398479 0.06060474]
  [0.00351576 0.02962968]]

 [[0.35321564 0.99306367]
  [0.04174224 0.9248683 ]
  [0.60623703 0.18810861]]

 [[0.51284495 0.33766755]
  [0.49983315 0.21540457]
  [0.37260222 0.41994215]]]


## Flatten N-Dimensional Array

In [116]:
arr = np.random.random((4,3,2))
arr.ndim

3

In [117]:
arr_flatten = arr.flatten()
arr_flatten.ndim

1

In [118]:
arr_ravel = arr.ravel()
arr_ravel.ndim

1

In [119]:
np.random.random(5)

array([0.77345356, 0.89003375, 0.58026685, 0.22034581, 0.83888468])

In [120]:
arr = np.arange(1, 100, 3)
print(arr.max())

97


In [121]:
arr.mean()

49.0

In [122]:
np.median(arr)

49.0

In [123]:
np.log(arr)

array([0.        , 1.38629436, 1.94591015, 2.30258509, 2.56494936,
       2.77258872, 2.94443898, 3.09104245, 3.21887582, 3.33220451,
       3.4339872 , 3.52636052, 3.61091791, 3.68887945, 3.76120012,
       3.8286414 , 3.8918203 , 3.95124372, 4.00733319, 4.06044301,
       4.11087386, 4.15888308, 4.20469262, 4.24849524, 4.29045944,
       4.33073334, 4.36944785, 4.40671925, 4.44265126, 4.47733681,
       4.51085951, 4.54329478, 4.57471098])

In [124]:
arr2 = np.random.random((5,5))
range_arr2 = arr2.max() - arr2.min()
range_arr2

0.9225024965259375